### ISSUE TITLE
"cannot load such file -- json-jwt (LoadError)"

### ISSUE THREAD

**Issue by merefield** [nov/json-jwt#82]
Getting this error:

"/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- json-jwt (LoadError)"

I'm seeing this in two completely separate environments, one of them running Ruby 2.6.3, and this one illustrated, running 2.5.5.

Am I doing something dumb?  thanks!

STR:

`gem install json-jwt`

output:
```
Fetching: bindata-2.4.4.gem (100%)
Successfully installed bindata-2.4.4
Fetching: aes_key_wrap-1.0.1.gem (100%)
Successfully installed aes_key_wrap-1.0.1
Fetching: json-jwt-1.10.2.gem (100%)
Successfully installed json-jwt-1.10.2
Parsing documentation for bindata-2.4.4
Installing ri documentation for bindata-2.4.4
Parsing documentation for aes_key_wrap-1.0.1
Installing ri documentation for aes_key_wrap-1.0.1
Parsing documentation for json-jwt-1.10.2
Installing ri documentation for json-jwt-1.10.2
Done installing documentation for bindata, aes_key_wrap, json-jwt after 2 seconds
3 gems installed
```

Simple test file  `mytest.rb`:

```
require 'json-jwt'
puts 'this worked!'
```

then run `ruby mytest.rb`

Leads to error:

```
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- json-jwt (LoadError)
```

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6.2
  - RUBY VERSION: 2.5.5 (2019-03-15 patchlevel 157) [arm-linux-gnueabihf]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /home/pi/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.5
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/pi/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - arm-linux
  - GEM PATHS:
     - /var/lib/gems/2.5.0
     - /home/pi/.gem/ruby/2.5.0
     - /usr/lib/arm-linux-gnueabihf/rubygems-integration/2.5.0
     - /usr/share/rubygems-integration/2.5.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/local/games
     - /usr/games
```

**Comment by merefield** [comment]
Apologies, I should have used `require 'json/jwt'`.  Closing issue

**Comment by myang1010** [comment]
@merefield, sorry to ask, but where did you put that `require 'jason/jwt'` ? Thank you.
